name: Deploy to WP Engine (Branch-Based Environment Detection)

on:
  push:
    branches:
      - revision/*  # Match all branches starting with "revision/"
      - develop     # Deploy to multiple environments on 'develop'
      - main        # Deploy to multiple environments on 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: ${{ github.ref_name }} # Use the current branch name
        # Define the environments for 'develop' and 'main', but allow all branches to run 
        include: # this is just for convenience in the steps below
          - branch: develop 
            environments: mmp3dev washrotaryadev eagleharbordev ragasdev esragdev rghfdev
          - branch: main
            environments: washrag eagleharbor ragas esrag rghg

    steps:
      - uses: actions/checkout@v3

      - name: Determine WP Engine Environment
        id: determine_environment
        run: |
          branch="${{ matrix.branch }}" # Assign to a variable for easier manipulation

          # Check for branch format (revision/*)
          if [[ "$branch" =~ ^revision/ ]]; then
            # Extract environment from branch name (using Bash substring removal)
            environment="${branch/revision\/}" 
            echo "environments=[$environment]" >> $GITHUB_OUTPUT # Array format for consistency
          elif [[ "$branch" == "main" ]]; then   # Handle main branch explicitly
            echo "environments=${{ matrix.environments }}" >> $GITHUB_OUTPUT
          else  # Default to 'mmp3dev' for develop branch
            echo "environments=mmp3dev" >> $GITHUB_OUTPUT 
          fi
          
      - name: Deploy to WP Engine Environments
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ matrix.env }}
          REMOTE_PATH: "wp-content/plugins/mmp-custom-form/"
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
        env:
          # Create a matrix variable for the environments
          matrix: ${{ fromJSON(steps.determine_environment.outputs.environments) }}
