name: Deploy to WP Engine (Branch-Based Environment Detection)

on:
  push:
    branches:
      - revision/**  # Match all branches starting with "revision/"
      - develop     
      - main       

jobs:
  determine_environment: # Separate job to determine environments
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_environment.outputs.environment }}
    steps:
      - name: Set Environment
        id: set_environment
        run: |
          branch="${{ github.ref_name }}" 

          if [[ "$branch" =~ ^revision/ ]]; then
            # Extract environment from branch name (using Bash substring removal)
            environment="${branch/revision\/}"
          elif [[ "$branch" == "main" ]]; then
            environment="washrag eagleharbor ragas esrag rghg" 
          else # Default to 'mmp3dev' for develop
            environment="mmp3dev washrotaryadev eagleharbordev ragasdev esragdev rghfdev"
          fi

          echo "environment=$environment" >> $GITHUB_OUTPUT

  deploy:
    needs: determine_environment # Ensure this job runs after determine_environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{fromJson(needs.determine_environment.outputs.environment)}}  # Use fromJson to parse

    steps:
      - uses: actions/checkout@v3
      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: ${{ matrix.env }}
          REMOTE_PATH: "wp-content/plugins/mmp-custom-form/"
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          CACHE_CLEAR: TRUE
